### ISSUE TITLE
Connect not possible

### ISSUE THREAD

**Issue by Draexl** [TA2k/ioBroker.bosch-ebike#11]
That are the log output from ioBroker:

	2023-12-01 18:46:34.962	error	instance system.adapter.bosch-ebike.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker
2023-12-01 18:46:34.962	error	Caught by controller[0]: at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
host.iobroker
2023-12-01 18:46:34.962	error	Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.iobroker
2023-12-01 18:46:34.961	error	Caught by controller[0]: at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:149:41)
host.iobroker
2023-12-01 18:46:34.961	error	Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'value')
host.iobroker
2023-12-01 18:46:34.960	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

bosch-ebike.0
2023-12-01 18:46:34.339	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

bosch-ebike.0
2023-12-01 18:46:34.313	error	Cannot read properties of undefined (reading 'value')

bosch-ebike.0
2023-12-01 18:46:34.312	error	TypeError: Cannot read properties of undefined (reading 'value') at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:149:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)

bosch-ebike.0
2023-12-01 18:46:34.310	error	unhandled promise rejection: Cannot read properties of undefined (reading 'value')

bosch-ebike.0
2023-12-01 18:46:34.308	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

admin.0
2023-12-01 18:45:36.024	warn	bosch-ebike has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"type"},"message":"must have required property 'type'"}]

**Comment by TA2k** [comment]
fixed with 0.1.5

**Comment by Draexl** [comment]
HI, connect not possible since 08 Jan. No Error logs inside ioBroker. The Adapter only yellow

**Comment by TA2k** [comment]
which type what is the debug log?

**Comment by Draexl** [comment]
After some minutes:
sch-ebike.0
2024-01-09 09:47:19.748	error	Error: getaddrinfo ENOTFOUND singlekey-id.comundefined

**Comment by TA2k** [comment]
please complete log with version and login type

**Comment by Draexl** [comment]
I changed the log type.
Version: 1.0.5
Login type: ebike Flow

bosch-ebike.0
2024-01-09 10:06:08.555	info	Login to eBike flow

bosch-ebike.0
2024-01-09 10:06:08.530	info	starting. Version 0.1.5 (non-npm: TA2k/ioBroker.bosch-ebike) in /opt/iobroker/node_modules/iobroker.bosch-ebike, node: v18.19.0, js-controller: 5.0.17

bosch-ebike.0
2024-01-09 10:06:08.136	debug	Plugin sentry Initialize Plugin (enabled=true)

bosch-ebike.0
2024-01-09 10:06:08.095	debug	States connected to redis: 127.0.0.1:9000

bosch-ebike.0
2024-01-09 10:06:08.015	debug	States create User PubSub Client

bosch-ebike.0
2024-01-09 10:06:08.014	debug	States create System PubSub Client

bosch-ebike.0
2024-01-09 10:06:07.994	debug	Redis States: Use Redis connection: 127.0.0.1:9000

bosch-ebike.0
2024-01-09 10:06:07.951	debug	Objects connected to redis: 127.0.0.1:9001

bosch-ebike.0
2024-01-09 10:06:07.899	debug	Objects client initialize lua scripts

bosch-ebike.0
2024-01-09 10:06:07.812	debug	Objects create User PubSub Client

bosch-ebike.0
2024-01-09 10:06:07.812	debug	Objects create System PubSub Client

bosch-ebike.0
2024-01-09 10:06:07.811	debug	Objects client ready ... initialize now

bosch-ebike.0
2024-01-09 10:06:07.774	debug	Redis Objects: Use Redis connection: 127.0.0.1:9001

**Comment by TA2k** [comment]
please use 0.1.6

**Comment by Draexl** [comment]
Works :-) Big thank you
