### ISSUE TITLE
iob Fehler im log; Adapter wird nicht grün

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.bosch-ebike#12]
Ich habe auch seit Heute im log:

```
host.iobroker
2023-12-02 10:38:18.898	error	instance system.adapter.bosch-ebike.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker
2023-12-02 10:38:18.898	error	Caught by controller[1]: at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
host.iobroker
2023-12-02 10:38:18.898	error	Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.iobroker
2023-12-02 10:38:18.898	error	Caught by controller[1]: at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:149:41)
host.iobroker
2023-12-02 10:38:18.898	error	Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'value')
host.iobroker
2023-12-02 10:38:18.898	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

bosch-ebike.0
2023-12-02 10:38:18.322	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

bosch-ebike.0
2023-12-02 10:38:18.321	info	terminating

bosch-ebike.0
2023-12-02 10:38:18.311	error	Cannot read properties of undefined (reading 'value')

bosch-ebike.0
2023-12-02 10:38:18.311	error	TypeError: Cannot read properties of undefined (reading 'value') at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:149:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)

bosch-ebike.0
2023-12-02 10:38:18.307	error	unhandled promise rejection: Cannot read properties of undefined (reading 'value')

bosch-ebike.0
2023-12-02 10:38:18.307	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

javascript.0
2023-12-02 10:38:17.427	info	script.js.Scripte.Licht.Flur2_EG: Licht Flur 2 EG ausgeschaltet.

bosch-ebike.0
2023-12-02 10:38:17.265	info	Login to eBike flow
```

Keine Veränderung durchgeführt. Und ich bin aktuell.
Habe auch gleich ein issue erstellt.

vgl auch thread:
https://forum.iobroker.net/topic/55902/test-adapter-bosch-ebik-connect-flow/59?_=1701509809315

**Comment by bahnuhr** [comment]
Habe 0.1.5 installiert.
Dann war alles ok.
