### ISSUE TITLE
Error im log: Unhandled promise rejection

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.bosch-ebike#28]
Im log kommt Error. Instanz bleibt rot.
V.0.1.7
flow

`<html>
<body>

host.iobroker | 2024-12-21 09:59:25.788 | info | Restart adapter system.adapter.bosch-ebike.0 because enabled
-- | -- | -- | --
host.iobroker | 2024-12-21 09:59:25.788 | error | instance system.adapter.bosch-ebike.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2024-12-21 09:59:25.788 | error | Caught by controller[1]: at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
host.iobroker | 2024-12-21 09:59:25.788 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.iobroker | 2024-12-21 09:59:25.788 | error | Caught by controller[1]: at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:198:65)
host.iobroker | 2024-12-21 09:59:25.788 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'split')
host.iobroker | 2024-12-21 09:59:25.788 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
bosch-ebike.0 | 2024-12-21 09:59:25.208 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
bosch-ebike.0 | 2024-12-21 09:59:25.208 | info | terminating
bosch-ebike.0 | 2024-12-21 09:59:25.198 | error | Cannot read properties of undefined (reading 'split')
bosch-ebike.0 | 2024-12-21 09:59:25.198 | error | TypeError: Cannot read properties of undefined (reading 'split') at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:198:65) at processTicksAndRejections (node:internal/process/task_queues:95:5) at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
bosch-ebike.0 | 2024-12-21 09:59:25.196 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'split')
bosch-ebike.0 | 2024-12-21 09:59:25.196 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bosch-ebike.0 | 2024-12-21 09:59:24.175 | info | Login to eBike flow

</body>
</html>`

**Comment by bahnuhr** [comment]
hier sieht man das log besser:
https://forum.iobroker.net/topic/55902/test-adapter-bosch-ebik-connect-flow/95?_=1734778368475

**Comment by marq24** [comment]
looks for me, that Bosch altered the requirments (again) - the post of the login/email now also make use of an additional form field `h-captcha-response` (but I could be totally wrong here)

**Comment by bahnuhr** [comment]
mit der 0.1.9 besteht der error noch:
`<html>
<body>

host.iobroker | 2024-12-30 10:22:28.476 | error | instance system.adapter.bosch-ebike.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.iobroker | 2024-12-30 10:22:28.476 | error | Caught by controller[1]: at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
host.iobroker | 2024-12-30 10:22:28.476 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.iobroker | 2024-12-30 10:22:28.476 | error | Caught by controller[1]: at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:204:65)
host.iobroker | 2024-12-30 10:22:28.476 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'split')
host.iobroker | 2024-12-30 10:22:28.475 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
bosch-ebike.0 | 2024-12-30 10:22:27.893 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
bosch-ebike.0 | 2024-12-30 10:22:27.892 | info | terminating
bosch-ebike.0 | 2024-12-30 10:22:27.883 | error | Cannot read properties of undefined (reading 'split')
bosch-ebike.0 | 2024-12-30 10:22:27.883 | error | TypeError: Cannot read properties of undefined (reading 'split') at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:204:65) at processTicksAndRejections (node:internal/process/task_queues:95:5) at BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
bosch-ebike.0 | 2024-12-30 10:22:27.881 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'split')
bosch-ebike.0 | 2024-12-30 10:22:27.880 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bosch-ebike.0 | 2024-12-30 10:22:27.150 | info | Login to eBike flow


</body>
</html>`

**Comment by bahnuhr** [comment]
von git installiert und es geht wieder.
Danke.
https://forum.iobroker.net/topic/55902/test-adapter-bosch-ebik-connect-flow/101
