### ISSUE TITLE
Adapter restart: Unhandled promise rejection

### ISSUE THREAD

**Issue by gitknd** [TA2k/ioBroker.bosch-ebike#3]
Nach einem Neustart der IOBroker Instanz bekomme ich plötzlich folgende Meldung (Login über Flow App geht):

<html>
<body>

bosch-ebike.0 | 2023-06-09 16:10:47.055 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
bosch-ebike.0 | 2023-06-09 16:10:47.053 | info | terminating
bosch-ebike.0 | 2023-06-09 16:10:47.043 | error | Cannot read properties of undefined (reading 'replace')
bosch-ebike.0 | 2023-06-09 16:10:47.042 | error | TypeError: Cannot read properties of undefined (reading 'replace') at BoschEbike.loginFlow (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:149:51) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async BoschEbike.onReady (/opt/iobroker/node_modules/iobroker.bosch-ebike/main.js:79:7)
bosch-ebike.0 | 2023-06-09 16:10:47.041 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'replace')
bosch-ebike.0 | 2023-06-09 16:10:47.040 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bosch-ebike.0 | 2023-06-09 16:10:45.643 | info | Login to eBike flow
bosch-ebike.0 | 2023-06-09 16:10:45.604 | info | starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.bosch-ebike, node: v18.16.0, js-controller: 4.0.24
bosch-ebike.0 | 2023-06-09 16:10:44.499 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

</body>
</html>

**Comment by SentiQ** [comment]
Login muss auf SingleKey umgestellt werden. Soll ich mich der Sache annehmen?

**Comment by gitknd** [comment]
Ja bitte unbedingt, das wäre super ;)

**Comment by lomtaslipptas** [comment]
Habe hier das gleiche Problem. Gibt es inzwischen eine Lösung @SentiQ ?

**Comment by TA2k** [comment]
Bitte 0.1.0 nutzen

**Comment by lomtaslipptas** [comment]
Danke, das hat funktioniert.
Kann der Thread hier dann nicht eigentlich als erledigt gekennzeichnet werden?
Und wieso ist im iobroker offiziellen Pool nur die 0.0.3 drin und nicht die 0.1.0? Konnte die nur über den Expertenmodus installieren...
